// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const SB_URL=Deno.env.get("SUPABASE_URL")!;
const SB_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const sb=createClient(SB_URL,SB_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const SELF=`${SB_URL}/functions/v1/iniflex-extra-large`;
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const reply=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"content-type":"application/json; charset=utf-8"}});
let PDF:any=null;
async function pdfjs(){if(PDF)return PDF;const m:any=await import("npm:pdfjs-dist@3.11.174/legacy/build/pdf.js");PDF=typeof m?.getDocument==="function"?m:m?.default;if(!PDF?.getDocument)throw new Error("pdfjs indisponível");if(PDF.GlobalWorkerOptions)PDF.GlobalWorkerOptions.workerSrc="";return PDF;}
async function keyOk(u:URL){const {data}=await sb.from("app_config").select("valor").eq("chave","cron_key").maybeSingle();return String(data?.valor||"").replace(/^"|"$/g,"")===String(u.searchParams.get("key")||"");}
async function sha(buf:ArrayBuffer){const h=await crypto.subtle.digest("SHA-256",buf);return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function fetchPdf(path:string){const r=await fetch(`${SB_URL}/storage/v1/object/relatorios-dia/${path}`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`},cache:"no-store"});if(!r.ok)throw new Error(`storage ${r.status} em ${path}`);return await r.arrayBuffer();}
async function pageLines(page:any){const tc=await page.getTextContent({disableCombineTextItems:false});const a:any[]=[];for(const it of tc.items||[]){const s=String(it?.str||"").trim();if(s)a.push({x:Number(it.transform?.[4]||0),y:Number(it.transform?.[5]||0),s});}a.sort((x,y)=>y.y-x.y||x.x-y.x);const g:any[]=[];for(const it of a){let z=g[g.length-1];if(!z||Math.abs(z.y-it.y)>=2.5){z={y:it.y,a:[]};g.push(z)}z.a.push(it)}return g.map(z=>z.a.sort((x:any,y:any)=>x.x-y.x).map((x:any)=>x.s).join(" ").replace(/\s+/g," ").trim()).filter(Boolean);}
function numBR(v:any){const s=String(v??"").trim().replace(/\s/g,"");if(!s)return null;const n=Number(s.includes(",")?s.replace(/\./g,"").replace(",","."):s);return Number.isFinite(n)?n:null;}
function dataBR(v:any){const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(String(v||"").trim());return m?`${m[3]}-${m[2]}-${m[1]}`:null;}
function dur(t:any){const s=String(t||"");const d=/(\d+)\s*d/.exec(s),h=/(\d+)\s*h/.exec(s),m=/(\d+)\s*m/.exec(s);return(!d&&!h&&!m)?null:(d?+d[1]*1440:0)+(h?+h[1]*60:0)+(m?+m[1]:0);}
function catDep(cod:any,nome:any){const n=String(nome||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();if(/RESERVAD|VENDID|FATURAD/.test(n))return"vendido";if(/CONTROLE DE QUALIDADE|\bCQ\b|DEVOLU|RETRABALH|BLOQUEAD|AVARIA|REPROVAD|QUARENTENA/.test(n))return"cq";if(/BOBINA|MATERIA.?PRIMA|RESINA|GRANULAD|MOIDO|RECICL|MASTER ?BATCH|PIGMENTO/.test(n))return"bobina";if(/ALMOXARIFAD|INSUMO|MATERIAIS|MATERIAL|MANUTENCAO|FERRAMENT|\bPECA|EPI\b|EXPEDIENTE|ESCRITORIO|LIMPEZA|LUBRIFIC|COMBUSTIVEL|ATIVO|IMOBILIZAD|SUCATA|INDUSTRIAL|ALMOX/.test(n))return"insumo";return"acabado";}
function schedule(jobId:string,key:string){const p=fetch(`${SELF}?action=chunk&job_id=${encodeURIComponent(jobId)}&key=${encodeURIComponent(key)}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).catch(()=>null);EdgeRuntime.waitUntil(p);}
async function markError(jobId:string|null,queueId:string|null,msg:string){const now=new Date().toISOString();if(jobId)await sb.from("iniflex_extra_jobs").update({status:"erro",erro:msg.slice(0,1000),lease_token:null,lease_until:null,atualizado_em:now}).eq("id",jobId);if(queueId)await sb.from("iniflex_pdf_queue").update({status:"erro",erro:msg.slice(0,1000),atualizado_em:now,processado_em:null}).eq("id",queueId);}
function headerInfo(lines:string[]){const text=lines.join("\n");const dm=/\bDATA:\s*(\d{2}\/\d{2}\/\d{4})/i.exec(text),hm=/\bHORA:\s*(\d{2}:\d{2}(?::\d{2})?)/i.exec(text);const pm=/(?:Per[ií]odo|Apontamentos):\s*(\d{2}\/\d{2}\/\d{4})\s*-\s*(\d{2}\/\d{2}\/\d{4})/i.exec(text);return{gerado:dataBR(dm?.[1]),hora:hm?.[1]||null,de:dataBR(pm?.[1]),ate:dataBR(pm?.[2]),text};}
function row(key:string,page:number,row:number,payload:any){return{dedupe_key:key,page_no:page,row_no:row,payload:{_type:"row",...payload}};}
function parse241(lines:string[],page:number,ctx:any){let dep=ctx.dep||null,last=ctx.last241||null;const out:any[]=[];const reItem=/^(\d{3,10})\s*\/\s*([A-Za-z0-9]+)\s+(?:(.*?)\s+)?([A-ZÇ][A-ZÇ0-9²³]{0,4})\s+(-?[\d.]*\d,\d+)\s+(-?[\d.]*\d,\d+)\s+(-?[\d.]*\d,\d+)\s+(-?[\d.]*\d,\d+)\s*$/;const reDep=/Dep[oó]sito:\s*(\d+)\s*[-–]\s*(.+)$/;const lixo=/^(ROTINA|DATA:|HORA:|P[ÁA]GINA|Rioplastic|Saldos de Estoque|Item\s+Descri|Total|Tipo\s|Ordem\s)/i;
  for(let i=0;i<lines.length;i++){const t=lines[i];let m=reDep.exec(t);if(m){dep={cod:m[1],nome:m[2].replace(/\s+(Tipo|Ordem)\s+[A-Za-zÀ-ú].*$/,"").trim()};last=null;continue;}m=reItem.exec(t);if(m&&dep){const quantidade=numBR(m[5]),peso=numBR(m[6]),unitario=numBR(m[7]),valor=numBR(m[8]);if(!quantidade&&!peso&&!valor){last=null;continue;}const p={dia_foto:ctx.gerado,hora_foto:ctx.hora,deposito_cod:dep.cod,deposito_nome:dep.nome,item_cod:m[1],item_versao:m[2],item_desc:String(m[3]||"").trim(),unidade:m[4],quantidade,peso,unitario,valor,categoria:catDep(dep.cod,dep.nome)};last={key:`${dep.cod}|${m[1]}|${m[2]}`,payload:p,page,row:i};out.push(row(last.key,page,i,p));continue;}if(/^\d{3,10}\s*\/\s*[A-Za-z0-9]+\s+.*(?:-?[\d.]*\d,\d+\s+){3}-?[\d.]*\d,\d+$/.test(t))throw new Error("REST241: linha não reconhecida na página "+page+". Importação bloqueada.");if(last&&!lixo.test(t)&&!/[\d.,]+,\d{2}/.test(t)&&!reDep.test(t)){last.payload.item_desc=(String(last.payload.item_desc||"")+" "+t).replace(/\s+/g," ").trim();out.push(row(last.key,page,i,last.payload));}}
  return{rows:out,ctx:{...ctx,dep,last241:last}};
}
function parsePedido(lines:string[],page:number,ctx:any){let regiao=ctx.regiao||null,sub=ctx.sub||null,cur=ctx.current||null;const out:any[]=[];const put=(i:number)=>{if(cur?.pedido)out.push(row(`PED|${cur.pedido}`,page,i,cur));};
  for(let i=0;i<lines.length;i++){const t=lines[i];let m;if((m=/^Região:\s*(.+?)\s*$/.exec(t))&&!/Sub-Regi/.test(t)){regiao=m[1].trim();continue;}if((m=/^Sub-Região:\s*(.+?)\s*$/.exec(t))){sub=m[1].trim();continue;}if(/^Pedido:/.test(t)){put(i);const ped=(/Pedido:\s*([\d]+)/.exec(t)||[])[1];if(!ped){cur=null;continue;}const emi=(/Emiss[ãa]o:\s*(\d{2}\/\d{2}\/\d{4})/.exec(t)||[])[1];const cid=(/Cidade\s*\/\s*UF:\s*(.+?)\s*(?:Fluxo\s*\/|Vendedor:|Transportador:|$)/.exec(t)||[])[1]||"";const flx=(/Fluxo\s*\/\s*Situa[çc][ãa]o:\s*(.+?)\s*(?:Vendedor:|Transportador:|$)/.exec(t)||[])[1]||"";const ven=(/Vendedor:\s*(.+?)\s*(?:Cond\.|Transportador:|$)/.exec(t)||[])[1]||"";const mv=/^(\d+)\s*-\s*(.+)$/.exec(ven.trim());const cl=cid.trim().replace(/\s*-\s*$/,"");const mc=/^(.*?)\s*-\s*([A-Z]{2})\s*$/.exec(cl);cur={pedido:ped,emissao:dataBR(emi),cidade:mc?mc[1].trim():(cl||null),uf:mc?mc[2]:null,regiao,sub_regiao:sub,vendedor_cod:mv?mv[1]:null,vendedor_nome:mv?mv[2].trim():(ven.trim()||null),cliente_cod:null,cliente_nome:null,situacao:flx.trim()||null,saldo_valor:0};continue;}if(!cur)continue;if((m=/^Cliente:\s*(\d+)\s*-\s*(.+?)\s*$/.exec(t))&&!cur.cliente_cod){cur.cliente_cod=m[1];cur.cliente_nome=m[2].replace(/\s+(Transportador|Cond\. Pagto\.|Fluxo\/Situa|Vendedor)\s*:.*$/i,"").trim();continue;}if(/^\d{6,7}\/\d+\s/.test(t)){const nums=t.match(/[\d.]+,\d{2}/g)||[];if(nums.length>=2){const v=numBR(nums.at(-1));if(v!=null&&v>0)cur.saldo_valor=Number(cur.saldo_valor||0)+v;}}}
  put(lines.length);return{rows:out,ctx:{...ctx,regiao,sub,current:cur}};
}
function parseProposta(lines:string[],page:number,ctx:any){let cur=ctx.current||null;const out:any[]=[];const put=(i:number)=>{if(cur?.proposta)out.push(row(`PROP|${cur.proposta}`,page,i,cur));};
  for(let i=0;i<lines.length;i++){const t=lines[i];let m;if(/^Proposta:/.test(t)){put(i);const n=(/Proposta:\s*(\d+)/.exec(t)||[])[1];if(!n){cur=null;continue;}const emi=(/Emiss[ãa]o:\s*(\d{2}\/\d{2}\/\d{4})/.exec(t)||[])[1];const flx=(/Fluxo\s*\/\s*Situa[çc][ãa]o:\s*(.+?)\s*(?:Vendedor:|Transportador:|$)/.exec(t)||[])[1]||"";cur={dia_foto:ctx.gerado,proposta:n,pedido:null,emissao:dataBR(emi),cliente_cod:null,cliente:null,entrega:null,situacao:flx.trim()||null,peso:null,rs_kg:null,qtde:null,rs_qtde:null,atendido:null,valor:null,ordem_compra:null};continue;}if(!cur)continue;if(/^(TRANSFORMAD|EM PEDIDOS)/i.test(t)&&cur.situacao&&!/TRANSFORMAD/i.test(cur.situacao)){cur.situacao=(cur.situacao+" "+t).replace(/\s+/g," ").trim();continue;}if((m=/^Cliente:\s*(\d+)\s*-\s*(.+?)\s*$/.exec(t))&&!cur.cliente_cod){cur.cliente_cod=m[1];cur.cliente=m[2].replace(/\s+(Transportador|Cond\. Pagto\.|Fluxo\/Situa|Vendedor)\s*:.*$/i,"").trim();continue;}if(/^\d{6,7}\/\d+\s/.test(t)){const de=(/\b(\d{2}\/\d{2}\/\d{4})\b/.exec(t)||[])[1];const iso=dataBR(de);if(iso&&(!cur.entrega||iso>cur.entrega))cur.entrega=iso;continue;}if(/^Total\s+Proposta:/.test(t)){const n=(t.match(/[\d.]+,\d{2}/g)||[]).map(numBR);if(n.length>=10){cur.qtde=n[3];cur.peso=n[6];cur.rs_kg=n[7];cur.valor=n[9];}else if(n.length>=5){cur.qtde=n[0];cur.valor=n.at(-1);cur.rs_kg=n.at(-3);cur.peso=n.at(-4);}}}
  put(lines.length);return{rows:out,ctx:{...ctx,current:cur}};
}
function parse304(lines:string[],page:number,ctx:any){let doc=ctx.doc||null;const out:any[]=[];const RX_DOC=/^Documento:\s*(\d+)\s*(?:Pedido Vendedor:\s*(.*?))?\s*Cliente:\s*(\d+)\s*-\s*(.+?)\s*$/;const RX_TOT=/^Tempo Total do Pedido:\s*(.+?)\s*$/;const RX_ETP=/^(\d{1,3})\s+(.+?)\s+(\d{2}\/\d{2}\/\d{4})\s+(\d{2}:\d{2})\s+((?:\d+\s*d\s*)?(?:\d+\s*h\s*)?\d+\s*m)\s*(.*)$/;
  for(let i=0;i<lines.length;i++){let L=lines[i];if(!L)continue;let m=RX_DOC.exec(L);if(m){doc={documento:m[1],pedido_vendedor:(m[2]||"").trim()||null,cliente_cod:m[3],cliente_nome:m[4].trim()};continue;}m=RX_TOT.exec(L);if(m&&doc){out.push({dedupe_key:`TOTAL|${doc.documento}`,page_no:page,row_no:i,payload:{_type:"total",documento:doc.documento,total_min:dur(m[1])}});continue;}if(!doc)continue;let e=RX_ETP.exec(L);if(!e&&/^\d{1,3}\s+\S/.test(L)&&lines[i+1]&&!RX_DOC.test(lines[i+1])&&!RX_TOT.test(lines[i+1])){e=RX_ETP.exec(L+" "+lines[i+1]);if(e)i++;}if(!e)continue;let c=0;while(c<2){const nx=lines[i+1];if(!nx||RX_DOC.test(nx)||RX_TOT.test(nx)||RX_ETP.test(nx)||/^\d{1,3}\s/.test(nx)||/\d{2}\/\d{2}\/\d{4}/.test(nx)||/^Seq\.|^Documento:|^Hist[óo]rico|^P[áa]gina|^ROTINA/i.test(nx))break;if(!/^[A-ZÁÂÃÉÊÍÓÔÕÚÇ][A-ZÁÂÃÉÊÍÓÔÕÚÇ\s.\-/]{1,38}$/.test(nx))break;if(!/(?:-|\.|\b(?:DE|DA|DO|DAS|DOS|E|EM|PARA|POR|COM|SEM|A|AO))\s*$/i.test(e[2]))break;e[2]+=" "+nx;i++;c++;}const etapa=e[2].replace(/\s*-\s*$/,"").replace(/\s+/g," ").trim(),cut=etapa.lastIndexOf(" - "),iso=dataBR(e[3]);if(ctx.periodo_inicio&&iso&&iso<ctx.periodo_inicio)continue;if(ctx.periodo_fim&&iso&&iso>ctx.periodo_fim)continue;const p={documento:doc.documento,pedido_vendedor:doc.pedido_vendedor,cliente_cod:doc.cliente_cod,cliente_nome:doc.cliente_nome,seq:+e[1],etapa,linha:cut>0?etapa.slice(0,cut).trim():null,setor:cut>0?etapa.slice(cut+3).trim():etapa,data_inclusao:`${iso}T${e[4]}:00-03:00`,tempo_min:dur(e[5]),usuario_inclusao:(e[6]||"").trim().slice(0,120)||null,usuario_repasse:null,ocorrencia:null,total_min:null};out.push(row(`${doc.documento}|${e[1]}`,page,i,p));}
  return{rows:out,ctx:{...ctx,doc}};
}
async function start(queueId:string,key:string){const {data:q,error:qe}=await sb.from("iniflex_pdf_queue").select("id,codigo,arquivo,caminho,periodo_inicio,periodo_fim,status").eq("id",queueId).maybeSingle();if(qe||!q)throw new Error("fila extra não encontrada");const code=String(q.codigo||"").toLowerCase();if(!["rest241","rven002-pedido","rven002-proposta","rven304"].includes(code))throw new Error(`código não suportado: ${code}`);const buf=await fetchPdf(q.caminho),hash=await sha(buf),lib=await pdfjs(),doc=await lib.getDocument({data:new Uint8Array(buf),disableWorker:true,isEvalSupported:false,useSystemFonts:false,disableFontFace:true,verbosity:0}).promise;const first:string[]=[];for(let p=1;p<=Math.min(2,doc.numPages);p++)first.push(...await pageLines(await doc.getPage(p)));const hi=headerInfo(first),head=hi.text;try{await doc.destroy()}catch(_){}
  if(code==="rest241"&&!(/ROTINA:\s*REST241/i.test(head)||/Saldos de Estoque por Dep[oó]sito/i.test(head)))throw new Error("PDF não é REST241");if(code.startsWith("rven002")&&!/ROTINA:\s*RVEN\s*002/i.test(head))throw new Error("PDF não é RVEN002");if(code==="rven002-pedido"&&!/Origem:\s*Pedido/i.test(head))throw new Error("RVEN002 não está com Origem Pedido");if(code==="rven002-proposta"&&!/Origem:\s*Proposta/i.test(head))throw new Error("RVEN002 não está com Origem Proposta");if(code==="rven304"&&!(/ROTINA:\s*RVEN\s*304/i.test(head)||/Hist[óo]rico do Fluxo de Venda do Documento/i.test(head)))throw new Error("PDF não é RVEN304");
  const {data:dup}=await sb.from("importacoes").select("id,registros").eq("hash",hash).maybeSingle();if(dup){const now=new Date().toISOString();await sb.from("iniflex_pdf_queue").update({status:"processado",erro:null,atualizado_em:now,processado_em:now}).eq("id",queueId);return{ok:true,duplicate:true,importacao_id:dup.id,registros:dup.registros};}
  const {data:old}=await sb.from("iniflex_extra_jobs").select("id,importacao_id,status,hash").eq("queue_id",queueId).maybeSingle();if(old?.status==="processando"&&old.hash===hash){schedule(old.id,key);return{ok:true,resumed:true,job_id:old.id};}if(old){if(old.importacao_id)await sb.from("importacoes").delete().eq("id",old.importacao_id);await sb.from("iniflex_extra_jobs").delete().eq("id",old.id);}
  const rotina=code==="rest241"?"241":code==="rven002-pedido"?"RVEN002":code==="rven002-proposta"?"PROP":"RVEN304";const pde=q.periodo_inicio||(code==="rven304"?hi.de:null)||hi.gerado;const pate=q.periodo_fim||(code==="rven304"?hi.ate:null)||hi.gerado;const {data:imp,error:ie}=await sb.from("importacoes").insert({hash,rotina,arquivo:q.arquivo,periodo_de:pde,periodo_ate:pate,registros:0,emissao:hi.gerado?`${hi.gerado}T${hi.hora||"00:00:00"}-03:00`:null}).select("id").single();if(ie||!imp)throw new Error(`importacoes: ${ie?.message||"sem id"}`);
  const ctx={gerado:hi.gerado,hora:hi.hora,periodo_inicio:q.periodo_inicio,periodo_fim:q.periodo_fim,origin:code.includes("proposta")?"Proposta":code.includes("pedido")?"Pedido":null};const {data:job,error:je}=await sb.from("iniflex_extra_jobs").insert({queue_id:queueId,codigo:code,caminho:q.caminho,arquivo:q.arquivo,hash,importacao_id:imp.id,periodo_inicio:pde,periodo_fim:pate,gerado:hi.gerado,hora:hi.hora,status:"processando",next_page:1,registros:0,ctx}).select("id").single();if(je||!job){await sb.from("importacoes").delete().eq("id",imp.id);throw new Error(`job extra: ${je?.message||"sem id"}`);}await sb.from("iniflex_pdf_queue").update({status:"processando",erro:null,atualizado_em:new Date().toISOString(),processado_em:null}).eq("id",queueId);schedule(job.id,key);return{ok:true,started:true,job_id:job.id,importacao_id:imp.id};}
async function chunk(jobId:string,key:string){const token=crypto.randomUUID(),now=new Date(),until=new Date(now.getTime()+180000).toISOString();const {data:job,error:ce}=await sb.from("iniflex_extra_jobs").update({lease_token:token,lease_until:until,atualizado_em:now.toISOString()}).eq("id",jobId).eq("status","processando").or(`lease_until.is.null,lease_until.lt.${now.toISOString()}`).select("*").maybeSingle();if(ce)throw new Error(`lease: ${ce.message}`);if(!job)return{ok:true,claimed:false};try{const buf=await fetchPdf(job.caminho),lib=await pdfjs(),doc=await lib.getDocument({data:new Uint8Array(buf),disableWorker:true,isEvalSupported:false,useSystemFonts:false,disableFontFace:true,verbosity:0}).promise,total=Number(doc.numPages||0),start=Number(job.next_page||1),batch=job.codigo==="rest241"?5:job.codigo==="rven304"?8:12,end=Math.min(total,start+batch-1);let ctx=job.ctx||{},rows:any[]=[];for(let p=start;p<=end;p++){const lines=await pageLines(await doc.getPage(p));let r;if(job.codigo==="rest241")r=parse241(lines,p,ctx);else if(job.codigo==="rven002-pedido")r=parsePedido(lines,p,ctx);else if(job.codigo==="rven002-proposta")r=parseProposta(lines,p,ctx);else r=parse304(lines,p,ctx);ctx=r.ctx;rows.push(...r.rows);}try{await doc.destroy()}catch(_){}const {data:comm,error:re}=await sb.rpc("iniflex_extra_commit_chunk",{p_job_id:jobId,p_lease_token:token,p_page_end:end,p_total_pages:total,p_ctx:ctx,p_rows:rows});if(re)throw new Error(`commit: ${re.message}`);const next=Number(comm?.[0]?.next_page||end+1);if(next>total){const {data:done,error:fe}=await sb.rpc("iniflex_extra_finalize",{p_job_id:jobId});if(fe)throw new Error(`finalizar: ${fe.message}`);return{ok:true,done:true,job_id:jobId,total_pages:total,result:done?.[0]||null};}schedule(jobId,key);return{ok:true,done:false,job_id:jobId,pages:[start,end],next_page:next,rows:rows.length};}catch(e){const msg=e instanceof Error?e.message:String(e);await markError(jobId,job.queue_id,msg);throw e;}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});const u=new URL(req.url);let queueId:string|null=null,jobId:string|null=null;try{if(!(await keyOk(u)))return reply({ok:false,error:"chave inválida"},401);const key=u.searchParams.get("key")||"",action=u.searchParams.get("action")||"start";queueId=u.searchParams.get("queue_id");jobId=u.searchParams.get("job_id");if(action==="start"){if(!queueId)return reply({ok:false,error:"queue_id ausente"},400);return reply(await start(queueId,key));}if(action==="chunk"){if(!jobId)return reply({ok:false,error:"job_id ausente"},400);return reply(await chunk(jobId,key));}if(action==="status"){const q=jobId?await sb.from("iniflex_extra_jobs").select("*").eq("id",jobId).maybeSingle():await sb.from("iniflex_extra_jobs").select("*").eq("queue_id",queueId).maybeSingle();return reply({ok:!q.error,job:q.data||null,error:q.error?.message||null});}return reply({ok:false,error:"ação inválida"},400);}catch(e){const msg=e instanceof Error?e.message:String(e);let linked=queueId;if(!linked&&jobId){const {data:j}=await sb.from("iniflex_extra_jobs").select("queue_id").eq("id",jobId).maybeSingle();linked=j?.queue_id||null;}await markError(jobId,linked,msg);return reply({ok:false,error:msg},200);}});